TEAM_STAT_COLUMNS = [
    "ToG",
    "ToSh",
    "AG",
    "ASh",
    "CeG",
    "CeSh",
    "EXG",
    "EXSh",
    "6mG",
    "6mSh",
    "PG",
    "PSh",
    "CoG",
    "CoSh",
    "PSOG",
    "PSOSh",
    "As",
    "To",
    "St",
    "Bl",
    "SpW",
    "Sp",
    "ExCe",
    "ExF",
    "DoEx",
    "P",
    "ExFin",
    "Ex4min",
]

TEAM_STAT_DB_MAP = {
    "ToG": "to_g",
    "ToSh": "to_sh",
    "AG": "a_g",
    "ASh": "a_sh",
    "CeG": "ce_g",
    "CeSh": "ce_sh",
    "EXG": "ex_g",
    "EXSh": "ex_sh",
    "6mG": "six_m_g",
    "6mSh": "six_m_sh",
    "PG": "p_g",
    "PSh": "p_sh",
    "CoG": "co_g",
    "CoSh": "co_sh",
    "PSOG": "pso_g",
    "PSOSh": "pso_sh",
    "As": "assists",
    "To": "turnovers",
    "St": "steals",
    "Bl": "blocks",
    "SpW": "sprints_won",
    "Sp": "sprints",
    "ExCe": "exclusions_drawn",
    "ExF": "exclusions_fouls",
    "DoEx": "double_exclusions",
    "P": "penalties",
    "ExFin": "exclusions_finished",
    "Ex4min": "exclusions_4min",
}
